### ISSUE TITLE
Unit.cs animator 호출

### ISSUE THREAD

**Issue by kimgaejin** [OruteZ/Project-H9#3]
Unit.cs의 animator 호출 시 null인지 검사하고, null이라면 GetComponent()를 수행하는 코드.
유니티 내 null 검사가 성능이 좋지도 않고, GetComponent 또한 성능이 좋지도 않으므로 null에 대한 예외처리가 되어있다 한들 초기화 단계에서만 animator를 확인하는 것이 좋음.
같은 클래스 내 SetUp() 함수에서 초기화를 해주거나, UnitModel.cs에서 animator를 받아두는게 맞다고 판단됨.

`
// 2023-11-07기준, 323번째 줄
    private Animator _animator;
    private static readonly int GET_HIT1 = Animator.StringToHash("GetHit1");
    private static readonly int DIE = Animator.StringToHash("Die");

    public Animator animator
    {
        get
        {
            if (_animator is null)
            {
                if (TryGetComponent(out _animator) is false)
                {
                    _animator = GetComponentInChildren<Animator>();
                }
            }

            return _animator;
        }
    }
`

**Comment by kimgaejin** [comment]
이거 원본글은 수정 안되나?

animator 호출하는 것 자체가 캐릭터의 외형(손,발,머리등의 위치정보)와 크게 상관하는 내용이기때문에 UnitModel.cs를 animator를 담는 그릇으로 사용하는 방향을 조금 더 추천할 것 같음.

결론적으로 언제 어떻게 수정하는가는 위 내용에 대해서 재오가 동의를 한다면, 이번 스프린트 끝나기 전 쯤 작업을 간단하게 진행할 수도 있고. 재오든 혁재든 여튼 저렇게 설계한 타당한 의도가 있었다 한다면 알려주길 바람.

**Comment by kimgaejin** [comment]
@OruteZ 와 멘션도 되네

**Comment by OruteZ** [comment]
미완성중 테스트 과정에서 lazy하게 할당하도록 했는데, 나름 문제없어서 그대로 뒀었네요. Setup에서 설정하도록 통일하는게 좋아 보입니다.

Model쪽으로 옮기는 건 한번 애니메이터 대규모 리펙토링할때 같이 진행해야 할 것 같아서, 이슈 남겨뒀다가 작업후 추가 코멘트 남길게요
